name: CI/CD for Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: gl1tchdm7/notes_api:latest

    - name: Logout from DockerHub
      run: docker logout
    
    - name: Trigger Render Deploy
      run: curl -X POST https://api.render.com/deploy/srv-cq575908fa8c7382fq3g?key=iqtakhmwpHo
